server:
  host: 127.0.0.1  # 配置服务器主机
  port: 8123       # 配置服务器端口

database:
  driver: mysql+pymysql
  host: localhost
  username: root
  password: 123456
  database: bytoken
  port: 3306

logging:
  log_level: DEBUG
  log_file: app.log
